-- Seed data: 200 problems + admin password

-- Admin password hash (text123) - SHA-256 precomputed for deployment

INSERT OR IGNORE INTO admin_settings (key, value) VALUES ('admin_password_hash', '99c24b7d36d81ac8c58e05e80d8f01ad0544bbcef5b9f04b20fe6666b2af47ae');

INSERT OR IGNORE INTO admin_settings (key, value) VALUES ('daily_mandatory_count', '2');
INSERT OR IGNORE INTO admin_settings (key, value) VALUES ('daily_max_random', '18');
INSERT OR IGNORE INTO admin_settings (key, value) VALUES ('mandatory_threshold', '1');

INSERT OR IGNORE INTO problems (nowcoder_id, title, difficulty, tags) VALUES ('1001', '[模拟][NOIP2007]字符串的展开', '模拟|NOIP2007', '["模拟", "NOIP2007"]');
INSERT OR IGNORE INTO problems (nowcoder_id, title, difficulty, tags) VALUES ('1002', '世界线', '', '[]');
INSERT OR IGNORE INTO problems (nowcoder_id, title, difficulty, tags) VALUES ('1003', '[指针优化]月月查华华的手机', '指针优化', '["指针优化"]');
INSERT OR IGNORE INTO problems (nowcoder_id, title, difficulty, tags) VALUES ('1004', '[贪心]华华听月月唱歌', '贪心', '["贪心"]');
INSERT OR IGNORE INTO problems (nowcoder_id, title, difficulty, tags) VALUES ('1005', '旅游的事前准备', '', '[]');
INSERT OR IGNORE INTO problems (nowcoder_id, title, difficulty, tags) VALUES ('1006', 'HamsterandEquation', '', '[]');
INSERT OR IGNORE INTO problems (nowcoder_id, title, difficulty, tags) VALUES ('1007', '[01分数规划]小咪买东西', '01分数规划', '["01分数规划"]');
INSERT OR IGNORE INTO problems (nowcoder_id, title, difficulty, tags) VALUES ('1008', '[模拟][NOIP2010]机器翻译', '模拟|NOIP2010', '["模拟", "NOIP2010"]');
INSERT OR IGNORE INTO problems (nowcoder_id, title, difficulty, tags) VALUES ('1009', '[枚举][NOIP2011]铺地毯', '枚举|NOIP2011', '["枚举", "NOIP2011"]');
INSERT OR IGNORE INTO problems (nowcoder_id, title, difficulty, tags) VALUES ('1010', '[枚举][NOIP2016]回文日期', '枚举|NOIP2016', '["枚举", "NOIP2016"]');
INSERT OR IGNORE INTO problems (nowcoder_id, title, difficulty, tags) VALUES ('1011', '[前缀和与差分][NOIP2005]校门外的树', '前缀和与差分|NOIP2005', '["前缀和与差分", "NOIP2005"]');
INSERT OR IGNORE INTO problems (nowcoder_id, title, difficulty, tags) VALUES ('1012', '[前缀和与差分][CQOI2009]中位数图', '前缀和与差分|CQOI2009', '["前缀和与差分", "CQOI2009"]');
INSERT OR IGNORE INTO problems (nowcoder_id, title, difficulty, tags) VALUES ('1013', '[前缀和与差分]二分', '前缀和与差分', '["前缀和与差分"]');
INSERT OR IGNORE INTO problems (nowcoder_id, title, difficulty, tags) VALUES ('1014', '[前缀和与差分]货仓选址', '前缀和与差分', '["前缀和与差分"]');
INSERT OR IGNORE INTO problems (nowcoder_id, title, difficulty, tags) VALUES ('1015', '[尺取法]字符串', '尺取法', '["尺取法"]');
INSERT OR IGNORE INTO problems (nowcoder_id, title, difficulty, tags) VALUES ('1016', '[尺取法]丢手绢', '尺取法', '["尺取法"]');
INSERT OR IGNORE INTO problems (nowcoder_id, title, difficulty, tags) VALUES ('1017', '[枚举+递推][SCOI2005]扫雷MINE', '枚举+递推|SCOI2005', '["枚举+递推", "SCOI2005"]');
INSERT OR IGNORE INTO problems (nowcoder_id, title, difficulty, tags) VALUES ('1018', '[状压枚举]牛可乐的翻转游戏', '状压枚举', '["状压枚举"]');
INSERT OR IGNORE INTO problems (nowcoder_id, title, difficulty, tags) VALUES ('1019', '[贪心][NOIP1998]拼数', '贪心|NOIP1998', '["贪心", "NOIP1998"]');
INSERT OR IGNORE INTO problems (nowcoder_id, title, difficulty, tags) VALUES ('1020', '[贪心][NOIP2008]排座椅', '贪心|NOIP2008', '["贪心", "NOIP2008"]');
INSERT OR IGNORE INTO problems (nowcoder_id, title, difficulty, tags) VALUES ('1021', '[贪心]矩阵消除游戏', '贪心', '["贪心"]');
INSERT OR IGNORE INTO problems (nowcoder_id, title, difficulty, tags) VALUES ('1022', '[推公式][NOIP2012]国王的游戏', '推公式|NOIP2012', '["推公式", "NOIP2012"]');
INSERT OR IGNORE INTO problems (nowcoder_id, title, difficulty, tags) VALUES ('1023', '[推公式][USACO 2007 Jan S]Protecting the Flowers', '推公式|USACO 2007 Jan S', '["推公式", "USACO 2007 Jan S"]');
INSERT OR IGNORE INTO problems (nowcoder_id, title, difficulty, tags) VALUES ('1024', '[按位贪心]毒瘤xor', '按位贪心', '["按位贪心"]');
INSERT OR IGNORE INTO problems (nowcoder_id, title, difficulty, tags) VALUES ('1025', '[按位贪心][NOI2014]起床困难综合症', '按位贪心|NOI2014', '["按位贪心", "NOI2014"]');
INSERT OR IGNORE INTO problems (nowcoder_id, title, difficulty, tags) VALUES ('1026', '[递归]The Biggest Water Problem', '递归', '["递归"]');
INSERT OR IGNORE INTO problems (nowcoder_id, title, difficulty, tags) VALUES ('1027', '[树状数组]求逆序数', '树状数组', '["树状数组"]');
INSERT OR IGNORE INTO problems (nowcoder_id, title, difficulty, tags) VALUES ('1028', '[递归]第k小数', '递归', '["递归"]');
INSERT OR IGNORE INTO problems (nowcoder_id, title, difficulty, tags) VALUES ('1029', '[递归]Bits', '递归', '["递归"]');
INSERT OR IGNORE INTO problems (nowcoder_id, title, difficulty, tags) VALUES ('1030', '[递归][NOIP2001]求先序排列', '递归|NOIP2001', '["递归", "NOIP2001"]');
INSERT OR IGNORE INTO problems (nowcoder_id, title, difficulty, tags) VALUES ('1031', '[递归]中序序列', '递归', '["递归"]');
INSERT OR IGNORE INTO problems (nowcoder_id, title, difficulty, tags) VALUES ('1032', '[分治][NOIP2004]FBI树', '分治|NOIP2004', '["分治", "NOIP2004"]');
INSERT OR IGNORE INTO problems (nowcoder_id, title, difficulty, tags) VALUES ('1033', '[分治]表达式计算4', '分治', '["分治"]');
INSERT OR IGNORE INTO problems (nowcoder_id, title, difficulty, tags) VALUES ('1034', '[分治]华华教月月做数学', '分治', '["分治"]');
INSERT OR IGNORE INTO problems (nowcoder_id, title, difficulty, tags) VALUES ('1035', '[二分查找]牛可乐和魔法封印', '二分查找', '["二分查找"]');
INSERT OR IGNORE INTO problems (nowcoder_id, title, difficulty, tags) VALUES ('1036', '[二分查找][USACO 2009 Dec S]Music Notes', '二分查找|USACO 2009 Dec S', '["二分查找", "USACO 2009 Dec S"]');
INSERT OR IGNORE INTO problems (nowcoder_id, title, difficulty, tags) VALUES ('1037', '[二分答案][NOIP2015]跳石头', '二分答案|NOIP2015', '["二分答案", "NOIP2015"]');
INSERT OR IGNORE INTO problems (nowcoder_id, title, difficulty, tags) VALUES ('1038', '[二分答案][USACO 2010 Feb S]Chocolate Eating', '二分答案|USACO 2010 Feb S', '["二分答案", "USACO 2010 Feb S"]');
INSERT OR IGNORE INTO problems (nowcoder_id, title, difficulty, tags) VALUES ('1039', '[二分答案]数字组合', '二分答案', '["二分答案"]');
INSERT OR IGNORE INTO problems (nowcoder_id, title, difficulty, tags) VALUES ('1040', '[二分答案][CQOI2010]扑克牌', '二分答案|CQOI2010', '["二分答案", "CQOI2010"]');
INSERT OR IGNORE INTO problems (nowcoder_id, title, difficulty, tags) VALUES ('1041', '[二分答案][NOIP2012]借教室', '二分答案|NOIP2012', '["二分答案", "NOIP2012"]');
INSERT OR IGNORE INTO problems (nowcoder_id, title, difficulty, tags) VALUES ('1042', '[二分答案]K-th Number', '二分答案', '["二分答案"]');
INSERT OR IGNORE INTO problems (nowcoder_id, title, difficulty, tags) VALUES ('1043', '[三分][SCOI2010]传送带', '三分|SCOI2010', '["三分", "SCOI2010"]');
INSERT OR IGNORE INTO problems (nowcoder_id, title, difficulty, tags) VALUES ('1044', '[栈]Rails', '栈', '["栈"]');
INSERT OR IGNORE INTO problems (nowcoder_id, title, difficulty, tags) VALUES ('1045', '[栈]牛牛与后缀表达式', '栈', '["栈"]');
INSERT OR IGNORE INTO problems (nowcoder_id, title, difficulty, tags) VALUES ('1046', '[栈]好串', '栈', '["栈"]');
INSERT OR IGNORE INTO problems (nowcoder_id, title, difficulty, tags) VALUES ('1047', '[队列]Keep In Line', '队列', '["队列"]');
INSERT OR IGNORE INTO problems (nowcoder_id, title, difficulty, tags) VALUES ('1048', '[堆][NOIP2004]合并果子', '堆|NOIP2004', '["堆", "NOIP2004"]');
INSERT OR IGNORE INTO problems (nowcoder_id, title, difficulty, tags) VALUES ('1049', '[队列][NOIP2016]蚯蚓', '队列|NOIP2016', '["队列", "NOIP2016"]');
INSERT OR IGNORE INTO problems (nowcoder_id, title, difficulty, tags) VALUES ('1050', '[双端队列]简单的数据结构', '双端队列', '["双端队列"]');
INSERT OR IGNORE INTO problems (nowcoder_id, title, difficulty, tags) VALUES ('1051', '[单调队列/栈]Sliding Window', '单调队列/栈', '["单调队列/栈"]');
INSERT OR IGNORE INTO problems (nowcoder_id, title, difficulty, tags) VALUES ('1052', '[单调队列/栈][USACO 2009 Mar S]Look Up', '单调队列/栈|USACO 2009 Mar S', '["单调队列/栈", "USACO 2009 Mar S"]');
INSERT OR IGNORE INTO problems (nowcoder_id, title, difficulty, tags) VALUES ('1053', '[单调队列/栈]Largest Rectangle in a Histogram', '单调队列/栈', '["单调队列/栈"]');
INSERT OR IGNORE INTO problems (nowcoder_id, title, difficulty, tags) VALUES ('1054', '[堆]第k小', '堆', '["堆"]');
INSERT OR IGNORE INTO problems (nowcoder_id, title, difficulty, tags) VALUES ('1055', '[对顶堆]Running Median', '对顶堆', '["对顶堆"]');
INSERT OR IGNORE INTO problems (nowcoder_id, title, difficulty, tags) VALUES ('1056', '[贪心][JSOI2010]缓存交换', '贪心|JSOI2010', '["贪心", "JSOI2010"]');
INSERT OR IGNORE INTO problems (nowcoder_id, title, difficulty, tags) VALUES ('1057', '[可后悔贪心]tokitsukaze and Soldier', '可后悔贪心', '["可后悔贪心"]');
INSERT OR IGNORE INTO problems (nowcoder_id, title, difficulty, tags) VALUES ('1058', '[可后悔贪心][JSOI2007]建筑抢修', '可后悔贪心|JSOI2007', '["可后悔贪心", "JSOI2007"]');
INSERT OR IGNORE INTO problems (nowcoder_id, title, difficulty, tags) VALUES ('1059', '[map/set]星球大战', 'map/set', '["map/set"]');
INSERT OR IGNORE INTO problems (nowcoder_id, title, difficulty, tags) VALUES ('1060', '[map/set]LetsPlayCurling', 'map/set', '["map/set"]');
INSERT OR IGNORE INTO problems (nowcoder_id, title, difficulty, tags) VALUES ('1061', '[map/set]任务', 'map/set', '["map/set"]');
INSERT OR IGNORE INTO problems (nowcoder_id, title, difficulty, tags) VALUES ('1062', '[偏序相关]牛可乐与NCPC', '偏序相关', '["偏序相关"]');
INSERT OR IGNORE INTO problems (nowcoder_id, title, difficulty, tags) VALUES ('1063', '[偏序相关]牛牛国的战争', '偏序相关', '["偏序相关"]');
INSERT OR IGNORE INTO problems (nowcoder_id, title, difficulty, tags) VALUES ('1064', '[并查集]DongDong认亲戚', '并查集', '["并查集"]');
INSERT OR IGNORE INTO problems (nowcoder_id, title, difficulty, tags) VALUES ('1065', '[并查集]叠积木', '并查集', '["并查集"]');
INSERT OR IGNORE INTO problems (nowcoder_id, title, difficulty, tags) VALUES ('1066', '[扩展域并查集][NOI2001]食物链', '扩展域并查集|NOI2001', '["扩展域并查集", "NOI2001"]');
INSERT OR IGNORE INTO problems (nowcoder_id, title, difficulty, tags) VALUES ('1067', '[扩展域并查集][NOIP2010]关押罪犯', '扩展域并查集|NOIP2010', '["扩展域并查集", "NOIP2010"]');
INSERT OR IGNORE INTO problems (nowcoder_id, title, difficulty, tags) VALUES ('1068', '[扩展域并查集]拆路', '扩展域并查集', '["扩展域并查集"]');
INSERT OR IGNORE INTO problems (nowcoder_id, title, difficulty, tags) VALUES ('1069', '[DFS]老子的全排列呢', 'DFS', '["DFS"]');
INSERT OR IGNORE INTO problems (nowcoder_id, title, difficulty, tags) VALUES ('1070', '[DFS]N皇后问题', 'DFS', '["DFS"]');
INSERT OR IGNORE INTO problems (nowcoder_id, title, difficulty, tags) VALUES ('1071', '[DFS]马踏棋盘', 'DFS', '["DFS"]');
INSERT OR IGNORE INTO problems (nowcoder_id, title, difficulty, tags) VALUES ('1072', '[DFS]数独挑战', 'DFS', '["DFS"]');
INSERT OR IGNORE INTO problems (nowcoder_id, title, difficulty, tags) VALUES ('1073', '[DFS][NOIP2017]奶酪', 'DFS|NOIP2017', '["DFS", "NOIP2017"]');
INSERT OR IGNORE INTO problems (nowcoder_id, title, difficulty, tags) VALUES ('1074', '[DFS]Lake Counting', 'DFS', '["DFS"]');
INSERT OR IGNORE INTO problems (nowcoder_id, title, difficulty, tags) VALUES ('1075', '[BFS]Jelly', 'BFS', '["BFS"]');
INSERT OR IGNORE INTO problems (nowcoder_id, title, difficulty, tags) VALUES ('1076', '[BFS]八数码', 'BFS', '["BFS"]');
INSERT OR IGNORE INTO problems (nowcoder_id, title, difficulty, tags) VALUES ('1077', '[BFS]几乎毁灭牛市的流星雨', 'BFS', '["BFS"]');
INSERT OR IGNORE INTO problems (nowcoder_id, title, difficulty, tags) VALUES ('1078', '[BFS][NOIP2002]字串变换', 'BFS|NOIP2002', '["BFS", "NOIP2002"]');
INSERT OR IGNORE INTO problems (nowcoder_id, title, difficulty, tags) VALUES ('1079', '[双向广搜]maze', '双向广搜', '["双向广搜"]');
INSERT OR IGNORE INTO problems (nowcoder_id, title, difficulty, tags) VALUES ('1080', '[双向广搜]洋流', '双向广搜', '["双向广搜"]');
INSERT OR IGNORE INTO problems (nowcoder_id, title, difficulty, tags) VALUES ('1081', '[搜索剪枝]小木棍', '搜索剪枝', '["搜索剪枝"]');
INSERT OR IGNORE INTO problems (nowcoder_id, title, difficulty, tags) VALUES ('1082', '[搜索剪枝][NOI1999]生日蛋糕', '搜索剪枝|NOI1999', '["搜索剪枝", "NOI1999"]');
INSERT OR IGNORE INTO problems (nowcoder_id, title, difficulty, tags) VALUES ('1083', '[搜索][NOIP2000]单词接龙', '搜索|NOIP2000', '["搜索", "NOIP2000"]');
INSERT OR IGNORE INTO problems (nowcoder_id, title, difficulty, tags) VALUES ('1084', '[搜索]魔法数字', '搜索', '["搜索"]');
INSERT OR IGNORE INTO problems (nowcoder_id, title, difficulty, tags) VALUES ('1085', '[搜索]新集合', '搜索', '["搜索"]');
INSERT OR IGNORE INTO problems (nowcoder_id, title, difficulty, tags) VALUES ('1086', '[搜索][SCOI2010]游戏', '搜索|SCOI2010', '["搜索", "SCOI2010"]');
INSERT OR IGNORE INTO problems (nowcoder_id, title, difficulty, tags) VALUES ('1087', '[搜索]Sramoc问题', '搜索', '["搜索"]');
INSERT OR IGNORE INTO problems (nowcoder_id, title, difficulty, tags) VALUES ('1088', '[搜索]Tree Decoration', '搜索', '["搜索"]');
INSERT OR IGNORE INTO problems (nowcoder_id, title, difficulty, tags) VALUES ('1089', '[搜索]孙悟空救师傅', '搜索', '["搜索"]');
INSERT OR IGNORE INTO problems (nowcoder_id, title, difficulty, tags) VALUES ('1090', '[搜索][NOIP2009]靶形数独', '搜索|NOIP2009', '["搜索", "NOIP2009"]');
INSERT OR IGNORE INTO problems (nowcoder_id, title, difficulty, tags) VALUES ('1091', '[搜索][NOIP2004]虫食算', '搜索|NOIP2004', '["搜索", "NOIP2004"]');
INSERT OR IGNORE INTO problems (nowcoder_id, title, difficulty, tags) VALUES ('1092', '[搜索]补天裂', '搜索', '["搜索"]');
INSERT OR IGNORE INTO problems (nowcoder_id, title, difficulty, tags) VALUES ('1093', '[递推]走楼梯', '递推', '["递推"]');
INSERT OR IGNORE INTO problems (nowcoder_id, title, difficulty, tags) VALUES ('1094', '[线性DP]数字三角形', '线性DP', '["线性DP"]');
INSERT OR IGNORE INTO problems (nowcoder_id, title, difficulty, tags) VALUES ('1095', '[线性DP][NOIP2002]过河卒', '线性DP|NOIP2002', '["线性DP", "NOIP2002"]');
INSERT OR IGNORE INTO problems (nowcoder_id, title, difficulty, tags) VALUES ('1096', '[线性DP][NOIP2008]传球游戏', '线性DP|NOIP2008', '["线性DP", "NOIP2008"]');
INSERT OR IGNORE INTO problems (nowcoder_id, title, difficulty, tags) VALUES ('1097', '[线性DP][NOIP1999]拦截导弹', '线性DP|NOIP1999', '["线性DP", "NOIP1999"]');
INSERT OR IGNORE INTO problems (nowcoder_id, title, difficulty, tags) VALUES ('1098', '[线性DP][NOIP2004]合唱队形', '线性DP|NOIP2004', '["线性DP", "NOIP2004"]');
INSERT OR IGNORE INTO problems (nowcoder_id, title, difficulty, tags) VALUES ('1099', '[线性DP]最大子串和', '线性DP', '["线性DP"]');
INSERT OR IGNORE INTO problems (nowcoder_id, title, difficulty, tags) VALUES ('1100', '[线性DP]牛可乐和最长公共子序列', '线性DP', '["线性DP"]');
INSERT OR IGNORE INTO problems (nowcoder_id, title, difficulty, tags) VALUES ('1101', '[01背包][NOIP2001]装箱问题', '01背包|NOIP2001', '["01背包", "NOIP2001"]');
INSERT OR IGNORE INTO problems (nowcoder_id, title, difficulty, tags) VALUES ('1102', '[01背包][NOIP2005]采药', '01背包|NOIP2005', '["01背包", "NOIP2005"]');
INSERT OR IGNORE INTO problems (nowcoder_id, title, difficulty, tags) VALUES ('1103', '[01背包][NOIP2006]开心的金明', '01背包|NOIP2006', '["01背包", "NOIP2006"]');
INSERT OR IGNORE INTO problems (nowcoder_id, title, difficulty, tags) VALUES ('1104', '[01背包]失衡天平', '01背包', '["01背包"]');
INSERT OR IGNORE INTO problems (nowcoder_id, title, difficulty, tags) VALUES ('1105', '[01背包]Steadily Growing Steam', '01背包', '["01背包"]');
INSERT OR IGNORE INTO problems (nowcoder_id, title, difficulty, tags) VALUES ('1106', '[完全背包][NOIP2018]货币系统', '完全背包|NOIP2018', '["完全背包", "NOIP2018"]');
INSERT OR IGNORE INTO problems (nowcoder_id, title, difficulty, tags) VALUES ('1107', '[多重背包]多重背包', '多重背包', '["多重背包"]');
INSERT OR IGNORE INTO problems (nowcoder_id, title, difficulty, tags) VALUES ('1108', '[分组背包][NOIP2006]金明的预算方案', '分组背包|NOIP2006', '["分组背包", "NOIP2006"]');
INSERT OR IGNORE INTO problems (nowcoder_id, title, difficulty, tags) VALUES ('1109', '[二维费用背包]队伍配置', '二维费用背包', '["二维费用背包"]');
INSERT OR IGNORE INTO problems (nowcoder_id, title, difficulty, tags) VALUES ('1110', '[超大背包]草药大师', '超大背包', '["超大背包"]');
INSERT OR IGNORE INTO problems (nowcoder_id, title, difficulty, tags) VALUES ('1111', '[区间DP]石子合并', '区间DP', '["区间DP"]');
INSERT OR IGNORE INTO problems (nowcoder_id, title, difficulty, tags) VALUES ('1112', '[区间DP]田忌赛马', '区间DP', '["区间DP"]');
INSERT OR IGNORE INTO problems (nowcoder_id, title, difficulty, tags) VALUES ('1113', '[区间DP]合并回文子串', '区间DP', '["区间DP"]');
INSERT OR IGNORE INTO problems (nowcoder_id, title, difficulty, tags) VALUES ('1114', '[区间DP][NOIP2007]矩阵取数游戏', '区间DP|NOIP2007', '["区间DP", "NOIP2007"]');
INSERT OR IGNORE INTO problems (nowcoder_id, title, difficulty, tags) VALUES ('1115', '[区间DP]迁徙过程中的河流', '区间DP', '["区间DP"]');
INSERT OR IGNORE INTO problems (nowcoder_id, title, difficulty, tags) VALUES ('1116', '[DP]最大m个子段和', 'DP', '["DP"]');
INSERT OR IGNORE INTO problems (nowcoder_id, title, difficulty, tags) VALUES ('1117', '[DP]To the Max', 'DP', '["DP"]');
INSERT OR IGNORE INTO problems (nowcoder_id, title, difficulty, tags) VALUES ('1118', '[DP]货船', 'DP', '["DP"]');
INSERT OR IGNORE INTO problems (nowcoder_id, title, difficulty, tags) VALUES ('1119', '[DP][NOIP2005]过河', 'DP|NOIP2005', '["DP", "NOIP2005"]');
INSERT OR IGNORE INTO problems (nowcoder_id, title, difficulty, tags) VALUES ('1120', '[DP]宝藏猎人', 'DP', '["DP"]');
INSERT OR IGNORE INTO problems (nowcoder_id, title, difficulty, tags) VALUES ('1121', '[DP]大魔法师牛可乐', 'DP', '["DP"]');
INSERT OR IGNORE INTO problems (nowcoder_id, title, difficulty, tags) VALUES ('1122', '[树形DP]小G有一个大树', '树形DP', '["树形DP"]');
INSERT OR IGNORE INTO problems (nowcoder_id, title, difficulty, tags) VALUES ('1123', '[树形DP]没有上司的舞会', '树形DP', '["树形DP"]');
INSERT OR IGNORE INTO problems (nowcoder_id, title, difficulty, tags) VALUES ('1124', '[树形DP]Strategic game', '树形DP', '["树形DP"]');
INSERT OR IGNORE INTO problems (nowcoder_id, title, difficulty, tags) VALUES ('1125', '[树形DP][USACO 2008 Jan G]Cell Phone Network', '树形DP|USACO 2008 Jan G', '["树形DP", "USACO 2008 Jan G"]');
INSERT OR IGNORE INTO problems (nowcoder_id, title, difficulty, tags) VALUES ('1126', '[树形DP]二叉苹果树', '树形DP', '["树形DP"]');
INSERT OR IGNORE INTO problems (nowcoder_id, title, difficulty, tags) VALUES ('1127', '[树形DP]树上子链', '树形DP', '["树形DP"]');
INSERT OR IGNORE INTO problems (nowcoder_id, title, difficulty, tags) VALUES ('1128', '[状压DP][SCOI2005]互不侵犯KING', '状压DP|SCOI2005', '["状压DP", "SCOI2005"]');
INSERT OR IGNORE INTO problems (nowcoder_id, title, difficulty, tags) VALUES ('1129', '[状压DP][NOI2001]炮兵阵地', '状压DP|NOI2001', '["状压DP", "NOI2001"]');
INSERT OR IGNORE INTO problems (nowcoder_id, title, difficulty, tags) VALUES ('1130', '[状压DP]郊区春游', '状压DP', '["状压DP"]');
INSERT OR IGNORE INTO problems (nowcoder_id, title, difficulty, tags) VALUES ('1131', '[状压DP]简单环', '状压DP', '["状压DP"]');
INSERT OR IGNORE INTO problems (nowcoder_id, title, difficulty, tags) VALUES ('1132', '[状压DP]Most Powerful', '状压DP', '["状压DP"]');
INSERT OR IGNORE INTO problems (nowcoder_id, title, difficulty, tags) VALUES ('1133', '[状压DP]mixup2混乱的奶牛', '状压DP', '["状压DP"]');
INSERT OR IGNORE INTO problems (nowcoder_id, title, difficulty, tags) VALUES ('1134', '[状压DP]Mondriaans Dream', '状压DP', '["状压DP"]');
INSERT OR IGNORE INTO problems (nowcoder_id, title, difficulty, tags) VALUES ('1135', '[DP][ZJOI2007]棋盘制作', 'DP|ZJOI2007', '["DP", "ZJOI2007"]');
INSERT OR IGNORE INTO problems (nowcoder_id, title, difficulty, tags) VALUES ('1136', '[DP][NOIP2008]传纸条', 'DP|NOIP2008', '["DP", "NOIP2008"]');
INSERT OR IGNORE INTO problems (nowcoder_id, title, difficulty, tags) VALUES ('1137', '[DP]Min酱要旅行', 'DP', '["DP"]');
INSERT OR IGNORE INTO problems (nowcoder_id, title, difficulty, tags) VALUES ('1138', '[DP][SCOI2009]粉刷匠', 'DP|SCOI2009', '["DP", "SCOI2009"]');
INSERT OR IGNORE INTO problems (nowcoder_id, title, difficulty, tags) VALUES ('1139', '[DP]打砖块(brike)', 'DP', '["DP"]');
INSERT OR IGNORE INTO problems (nowcoder_id, title, difficulty, tags) VALUES ('1140', '[DP]树学', 'DP', '["DP"]');
INSERT OR IGNORE INTO problems (nowcoder_id, title, difficulty, tags) VALUES ('1141', '[拓扑排序][NOIP2003]神经网络', '拓扑排序|NOIP2003', '["拓扑排序", "NOIP2003"]');
INSERT OR IGNORE INTO problems (nowcoder_id, title, difficulty, tags) VALUES ('1142', '[拓扑排序][HNOI2015]菜肴制作', '拓扑排序|HNOI2015', '["拓扑排序", "HNOI2015"]');
INSERT OR IGNORE INTO problems (nowcoder_id, title, difficulty, tags) VALUES ('1143', '[拓扑排序]任务安排', '拓扑排序', '["拓扑排序"]');
INSERT OR IGNORE INTO problems (nowcoder_id, title, difficulty, tags) VALUES ('1144', '[最短路]公交线路', '最短路', '["最短路"]');
INSERT OR IGNORE INTO problems (nowcoder_id, title, difficulty, tags) VALUES ('1145', '[最短路]Rinne Loves Graph', '最短路', '["最短路"]');
INSERT OR IGNORE INTO problems (nowcoder_id, title, difficulty, tags) VALUES ('1146', '[最短路]胖胖的牛牛', '最短路', '["最短路"]');
INSERT OR IGNORE INTO problems (nowcoder_id, title, difficulty, tags) VALUES ('1147', '[最短路]分层图最短路', '最短路', '["最短路"]');
INSERT OR IGNORE INTO problems (nowcoder_id, title, difficulty, tags) VALUES ('1148', '[最短路]传送门', '最短路', '["最短路"]');
INSERT OR IGNORE INTO problems (nowcoder_id, title, difficulty, tags) VALUES ('1149', '[最短路][USACO 2007 Mar G]Ranking the Cows', '最短路|USACO 2007 Mar G', '["最短路", "USACO 2007 Mar G"]');
INSERT OR IGNORE INTO problems (nowcoder_id, title, difficulty, tags) VALUES ('1150', '[最短路]瘦了的牛牛去旅游', '最短路', '["最短路"]');
INSERT OR IGNORE INTO problems (nowcoder_id, title, difficulty, tags) VALUES ('1151', '[最短路图][HAOI2012]ROAD', '最短路图|HAOI2012', '["最短路图", "HAOI2012"]');
INSERT OR IGNORE INTO problems (nowcoder_id, title, difficulty, tags) VALUES ('1152', '[最短路图][NOIP2017]逛公园', '最短路图|NOIP2017', '["最短路图", "NOIP2017"]');
INSERT OR IGNORE INTO problems (nowcoder_id, title, difficulty, tags) VALUES ('1153', '[差分约束][SCOI2011]糖果', '差分约束|SCOI2011', '["差分约束", "SCOI2011"]');
INSERT OR IGNORE INTO problems (nowcoder_id, title, difficulty, tags) VALUES ('1154', '[最小生成树]挖沟', '最小生成树', '["最小生成树"]');
INSERT OR IGNORE INTO problems (nowcoder_id, title, difficulty, tags) VALUES ('1155', '[最小生成树]道路建设', '最小生成树', '["最小生成树"]');
INSERT OR IGNORE INTO problems (nowcoder_id, title, difficulty, tags) VALUES ('1156', '[最小生成树]Forsaken喜欢独一无二的树', '最小生成树', '["最小生成树"]');
INSERT OR IGNORE INTO problems (nowcoder_id, title, difficulty, tags) VALUES ('1157', '[最小生成树][SCOI2012]滑雪与时间胶囊', '最小生成树|SCOI2012', '["最小生成树", "SCOI2012"]');
INSERT OR IGNORE INTO problems (nowcoder_id, title, difficulty, tags) VALUES ('1158', '[数论]素数判断', '数论', '["数论"]');
INSERT OR IGNORE INTO problems (nowcoder_id, title, difficulty, tags) VALUES ('1159', '[数论]素数的个数', '数论', '["数论"]');
INSERT OR IGNORE INTO problems (nowcoder_id, title, difficulty, tags) VALUES ('1160', '[数论]最大公约数(lcm)', '数论', '["数论"]');
INSERT OR IGNORE INTO problems (nowcoder_id, title, difficulty, tags) VALUES ('1161', '[数论]华华对月月的忠诚', '数论', '["数论"]');
INSERT OR IGNORE INTO problems (nowcoder_id, title, difficulty, tags) VALUES ('1162', '[数论][SDOI2008]仪仗队', '数论|SDOI2008', '["数论", "SDOI2008"]');
INSERT OR IGNORE INTO problems (nowcoder_id, title, difficulty, tags) VALUES ('1163', '[数论]同余方程', '数论', '["数论"]');
INSERT OR IGNORE INTO problems (nowcoder_id, title, difficulty, tags) VALUES ('1164', '[数论]分糖果', '数论', '["数论"]');
INSERT OR IGNORE INTO problems (nowcoder_id, title, difficulty, tags) VALUES ('1165', '[数论]漂亮数', '数论', '["数论"]');
INSERT OR IGNORE INTO problems (nowcoder_id, title, difficulty, tags) VALUES ('1166', '[数论]华华给月月出题', '数论', '["数论"]');
INSERT OR IGNORE INTO problems (nowcoder_id, title, difficulty, tags) VALUES ('1167', '[数论]只能吃土豆的牛牛', '数论', '["数论"]');
INSERT OR IGNORE INTO problems (nowcoder_id, title, difficulty, tags) VALUES ('1168', '[数论][NOIP2009]Hankson的趣味题', '数论|NOIP2009', '["数论", "NOIP2009"]');
INSERT OR IGNORE INTO problems (nowcoder_id, title, difficulty, tags) VALUES ('1169', '[数论]集合与最大公因数', '数论', '["数论"]');
INSERT OR IGNORE INTO problems (nowcoder_id, title, difficulty, tags) VALUES ('1170', '[排列组合][NOIP2011]计算系数', '排列组合|NOIP2011', '["排列组合", "NOIP2011"]');
INSERT OR IGNORE INTO problems (nowcoder_id, title, difficulty, tags) VALUES ('1171', '[排列组合][HAOI2012]容易题(EASY)', '排列组合|HAOI2012', '["排列组合", "HAOI2012"]');
INSERT OR IGNORE INTO problems (nowcoder_id, title, difficulty, tags) VALUES ('1172', '[排列组合][HAOI2016]放棋子', '排列组合|HAOI2016', '["排列组合", "HAOI2016"]');
INSERT OR IGNORE INTO problems (nowcoder_id, title, difficulty, tags) VALUES ('1173', '[排列组合]Little Devil I', '排列组合', '["排列组合"]');
INSERT OR IGNORE INTO problems (nowcoder_id, title, difficulty, tags) VALUES ('1174', '[容斥]大水题', '容斥', '["容斥"]');
INSERT OR IGNORE INTO problems (nowcoder_id, title, difficulty, tags) VALUES ('1175', '[容斥]青蛙', '容斥', '["容斥"]');
INSERT OR IGNORE INTO problems (nowcoder_id, title, difficulty, tags) VALUES ('1176', '[容斥]最后的晚餐(dinner)', '容斥', '["容斥"]');
INSERT OR IGNORE INTO problems (nowcoder_id, title, difficulty, tags) VALUES ('1177', '[线性代数]愉快的递推式', '线性代数', '["线性代数"]');
INSERT OR IGNORE INTO problems (nowcoder_id, title, difficulty, tags) VALUES ('1178', '[线性代数]又见斐波那契', '线性代数', '["线性代数"]');
INSERT OR IGNORE INTO problems (nowcoder_id, title, difficulty, tags) VALUES ('1179', '[博弈论]石子游戏', '博弈论', '["博弈论"]');
INSERT OR IGNORE INTO problems (nowcoder_id, title, difficulty, tags) VALUES ('1180', '[博弈论]红色和紫色', '博弈论', '["博弈论"]');
INSERT OR IGNORE INTO problems (nowcoder_id, title, difficulty, tags) VALUES ('1181', '[博弈论]Game', '博弈论', '["博弈论"]');
INSERT OR IGNORE INTO problems (nowcoder_id, title, difficulty, tags) VALUES ('1182', '[博弈论]取石子游戏 2', '博弈论', '["博弈论"]');
INSERT OR IGNORE INTO problems (nowcoder_id, title, difficulty, tags) VALUES ('1183', '[博弈论]石子游戏', '博弈论', '["博弈论"]');
INSERT OR IGNORE INTO problems (nowcoder_id, title, difficulty, tags) VALUES ('1184', '[博弈论]二叉树游戏', '博弈论', '["博弈论"]');
INSERT OR IGNORE INTO problems (nowcoder_id, title, difficulty, tags) VALUES ('1185', '[博弈论]序列游戏', '博弈论', '["博弈论"]');
INSERT OR IGNORE INTO problems (nowcoder_id, title, difficulty, tags) VALUES ('1186', '[概率]Happy Running', '概率', '["概率"]');
INSERT OR IGNORE INTO problems (nowcoder_id, title, difficulty, tags) VALUES ('1187', '[概率]分蛋糕', '概率', '["概率"]');
INSERT OR IGNORE INTO problems (nowcoder_id, title, difficulty, tags) VALUES ('1188', '[数论分块]因数个数和', '数论分块', '["数论分块"]');
INSERT OR IGNORE INTO problems (nowcoder_id, title, difficulty, tags) VALUES ('1189', '[数论分块]小G的约数', '数论分块', '["数论分块"]');
INSERT OR IGNORE INTO problems (nowcoder_id, title, difficulty, tags) VALUES ('1190', '[数论分块]浅尝辄止', '数论分块', '["数论分块"]');
INSERT OR IGNORE INTO problems (nowcoder_id, title, difficulty, tags) VALUES ('1191', '[线段树]A Simple Problem with Integers', '线段树', '["线段树"]');
INSERT OR IGNORE INTO problems (nowcoder_id, title, difficulty, tags) VALUES ('1192', '[线段树]区区区间', '线段树', '["线段树"]');
INSERT OR IGNORE INTO problems (nowcoder_id, title, difficulty, tags) VALUES ('1193', '[线段树]整数序列', '线段树', '["线段树"]');
INSERT OR IGNORE INTO problems (nowcoder_id, title, difficulty, tags) VALUES ('1194', '[线段树]序列求和', '线段树', '["线段树"]');
INSERT OR IGNORE INTO problems (nowcoder_id, title, difficulty, tags) VALUES ('1195', '[线段树]数星星 Stars', '线段树', '["线段树"]');
INSERT OR IGNORE INTO problems (nowcoder_id, title, difficulty, tags) VALUES ('1196', '[线段树]牛牛的最美味和最不美味的零食', '线段树', '["线段树"]');
INSERT OR IGNORE INTO problems (nowcoder_id, title, difficulty, tags) VALUES ('1197', '[线段树]连续区间的最大公约数', '线段树', '["线段树"]');
INSERT OR IGNORE INTO problems (nowcoder_id, title, difficulty, tags) VALUES ('1198', '[线段树]统计颜色', '线段树', '["线段树"]');
INSERT OR IGNORE INTO problems (nowcoder_id, title, difficulty, tags) VALUES ('1199', '[线段树]Runaway', '线段树', '["线段树"]');
INSERT OR IGNORE INTO problems (nowcoder_id, title, difficulty, tags) VALUES ('1200', '[线段树][SDOI2015]道路修建', '线段树|SDOI2015', '["线段树", "SDOI2015"]');